** part 1 **

In [1]:
import numpy as np


In [2]:
lis=[2,3,4]
print(lis)

[2, 3, 4]


In [3]:
print(" 1 D array")

a=np.array([1,2,3])
print(a)

#______________

print("2D array")

b=np.array([[4,5,6],[5,6,7]])
print(b)

#------------------

print("3D array")

c=np.array([[[1,2,3],[4,5,6],[7,8,9]]])
print(c)

 1 D array
[1 2 3]
2D array
[[4 5 6]
 [5 6 7]]
3D array
[[[1 2 3]
  [4 5 6]
  [7 8 9]]]


** type **

In [6]:
type(a)

numpy.ndarray

In [5]:
type(b)

numpy.ndarray

** size = tell the no.of elements in an array ** 

In [7]:
print(a.size)
print(b.size)
print(c.size)

3
6
9


** shape= (rows,cols) **

In [8]:
print(a.shape)
print(b.shape)
print(c.shape)

(3,)
(2, 3)
(1, 3, 3)


** dtype=type of data present in the array **

In [9]:
print(a.dtype)
print(b.dtype)
print(c.dtype)

int64
int64
int64


In [10]:
d=np.array([[[[2.3,4,5],[3.5,1,2],[4.7,2.4,5],[5.2,4,6.0]]]])
print(d)

[[[[2.3 4.  5. ]
   [3.5 1.  2. ]
   [4.7 2.4 5. ]
   [5.2 4.  6. ]]]]


In [11]:
print(d.shape)
print(d.dtype)

(1, 1, 4, 3)
float64


** transpose = change row to colum and column to row**

In [15]:
d.transpose()

array([[[[2.3]],

        [[3.5]],

        [[4.7]],

        [[5.2]]],


       [[[4. ]],

        [[1. ]],

        [[2.4]],

        [[4. ]]],


       [[[5. ]],

        [[2. ]],

        [[5. ]],

        [[6. ]]]])

In [16]:
d.transpose()

array([[[[2.3]],

        [[3.5]],

        [[4.7]],

        [[5.2]]],


       [[[4. ]],

        [[1. ]],

        [[2.4]],

        [[4. ]]],


       [[[5. ]],

        [[2. ]],

        [[5. ]],

        [[6. ]]]])

** part 2 **

In [18]:
np.empty((4,4),dtype=int)

array([[25895968444448860, 23925768161198147, 32370111954616435,
        29273895798374492],
       [25896114476679273, 27866439313391713, 27303502244872303,
        29555198978162739],
       [29555366481887330, 31525390671741044, 27303532308922465,
        25896191785238631],
       [28147970123825264, 26740517932040289, 29555345007902815,
        12948256956809332]])

In [19]:
np.empty((1,1),dtype=float)

array([[8.34443015e-308]])

** ones **

In [20]:
np.ones(6)

array([1., 1., 1., 1., 1., 1.])

In [22]:
np.ones((2,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [23]:
np.ones((3,4),dtype=int)

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [25]:
np.ones((3,4),dtype=str)

array([['1', '1', '1', '1'],
       ['1', '1', '1', '1'],
       ['1', '1', '1', '1']], dtype='<U1')

** zeros **

In [26]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [27]:
np.zeros((3,3),dtype=int)

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [28]:
np.zeros((3,3),dtype=bool)

array([[False, False, False],
       [False, False, False],
       [False, False, False]])

In [29]:
np.ones((3,3),dtype=bool)

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

** part 3 **

** arange **

it same as forloop

a=np.arange(start, end, increment)

In [34]:
a=np.arange(2)
print(a)

[0 1]


In [35]:
a=np.arange(1,20)
print(a)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


In [36]:
a=np.arange(2,20,2)
print(a)

[ 2  4  6  8 10 12 14 16 18]


** reshape  **


** reshape  the aranged value**

In [4]:
import numpy as np

a = np.arange(6)
a = a.reshape((2, 3))
a

array([[0, 1, 2],
       [3, 4, 5]])

i am going to bild large number of array

In [7]:
a=np.arange(1,100,2)
a

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33,
       35, 37, 39, 41, 43, 45, 47, 49, 51, 53, 55, 57, 59, 61, 63, 65, 67,
       69, 71, 73, 75, 77, 79, 81, 83, 85, 87, 89, 91, 93, 95, 97, 99])

rearrange the shape of an array is 10 row and 5 column

In [8]:
a=a.reshape(10,5)
a

array([[ 1,  3,  5,  7,  9],
       [11, 13, 15, 17, 19],
       [21, 23, 25, 27, 29],
       [31, 33, 35, 37, 39],
       [41, 43, 45, 47, 49],
       [51, 53, 55, 57, 59],
       [61, 63, 65, 67, 69],
       [71, 73, 75, 77, 79],
       [81, 83, 85, 87, 89],
       [91, 93, 95, 97, 99]])

** flatten **
used for change the multidimentional array to one dimentional (1 row multiple column)

In [9]:
b=a.flatten()
b

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33,
       35, 37, 39, 41, 43, 45, 47, 49, 51, 53, 55, 57, 59, 61, 63, 65, 67,
       69, 71, 73, 75, 77, 79, 81, 83, 85, 87, 89, 91, 93, 95, 97, 99])

** ravel **

In [10]:
b=a.ravel()
b

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33,
       35, 37, 39, 41, 43, 45, 47, 49, 51, 53, 55, 57, 59, 61, 63, 65, 67,
       69, 71, 73, 75, 77, 79, 81, 83, 85, 87, 89, 91, 93, 95, 97, 99])

** part 4 **

In [13]:
a=np.arange(1,51)
a=a.reshape(5,10)
print(a)

[[ 1  2  3  4  5  6  7  8  9 10]
 [11 12 13 14 15 16 17 18 19 20]
 [21 22 23 24 25 26 27 28 29 30]
 [31 32 33 34 35 36 37 38 39 40]
 [41 42 43 44 45 46 47 48 49 50]]


In [14]:
a[0]

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [15]:
a[2]

array([21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

In [16]:
a[: :]

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15, 16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25, 26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35, 36, 37, 38, 39, 40],
       [41, 42, 43, 44, 45, 46, 47, 48, 49, 50]])

In [17]:
a[2:5]

array([[21, 22, 23, 24, 25, 26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35, 36, 37, 38, 39, 40],
       [41, 42, 43, 44, 45, 46, 47, 48, 49, 50]])

In [18]:
a[: 4]

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15, 16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25, 26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35, 36, 37, 38, 39, 40]])

In [19]:
a[2,3]

np.int64(24)

In [20]:
a[:,2]

array([ 3, 13, 23, 33, 43])

** part 5 **

In [22]:
a=np.arange(1,51)
a=a.reshape(10,5)
print(a)

b=np.arange(1,51)
b=b.reshape(10,5)
print(b)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]
 [26 27 28 29 30]
 [31 32 33 34 35]
 [36 37 38 39 40]
 [41 42 43 44 45]
 [46 47 48 49 50]]
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]
 [26 27 28 29 30]
 [31 32 33 34 35]
 [36 37 38 39 40]
 [41 42 43 44 45]
 [46 47 48 49 50]]


In [23]:
a+b

array([[  2,   4,   6,   8,  10],
       [ 12,  14,  16,  18,  20],
       [ 22,  24,  26,  28,  30],
       [ 32,  34,  36,  38,  40],
       [ 42,  44,  46,  48,  50],
       [ 52,  54,  56,  58,  60],
       [ 62,  64,  66,  68,  70],
       [ 72,  74,  76,  78,  80],
       [ 82,  84,  86,  88,  90],
       [ 92,  94,  96,  98, 100]])

In [25]:
np.add(a,b)

array([[  2,   4,   6,   8,  10],
       [ 12,  14,  16,  18,  20],
       [ 22,  24,  26,  28,  30],
       [ 32,  34,  36,  38,  40],
       [ 42,  44,  46,  48,  50],
       [ 52,  54,  56,  58,  60],
       [ 62,  64,  66,  68,  70],
       [ 72,  74,  76,  78,  80],
       [ 82,  84,  86,  88,  90],
       [ 92,  94,  96,  98, 100]])

In [26]:
np.sum(b)

np.int64(1275)

In [27]:
np.sum(b,axis=1)

array([ 15,  40,  65,  90, 115, 140, 165, 190, 215, 240])

** part 7 **

In [28]:
np.random.random(1)

array([0.21508857])

In [30]:
np.random.randint(1,10)

6

In [32]:
np.random.random(2)

array([0.89456959, 0.61993592])

In [34]:
np.random.random((2,2))

array([[0.67715556, 0.14188371],
       [0.00988355, 0.13649418]])

In [35]:
np.random.randint(1,10,(2,2))

array([[4, 2],
       [4, 6]], dtype=int32)

In [36]:
a=np.arange(1,10)
print(a)

[1 2 3 4 5 6 7 8 9]


In [38]:
np.random.choice(a)

np.int64(4)

** part 8 **

In [47]:
s1="good sound"
s2="bye"

In [41]:
np.char.add(s1,s2)

np.str_('goodbye')

In [42]:
np.char.upper(s1)

array('GOOD', dtype='<U4')

In [43]:
np.char.lower(s2)

array('bye', dtype='<U3')

In [48]:
np.char.split(s1)

array(list(['good', 'sound']), dtype=object)

In [50]:
print(np.char.center("good",80,"*"))

**************************************good**************************************
